site_name: User Documentation Project JJ
theme:
    name: mkdocs
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.path
